/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.brown.csci2951k.ui;

import edu.brown.csci2951k.models.data.MObjectSet;
import edu.brown.csci2951k.models.distribution.MultinomialDistribution;
import java.awt.Color;
import java.util.Optional;

/**
 *
 * @author Gaurav Manek
 * @param <T>
 */
public class FrmMultinomialVisualizer extends javax.swing.JFrame {
    
    private final PnlMultinomialVizualizer pnl;

    /**
     * Creates new form FrmMultinomialVisualizer
     * @param objs
     */
    public FrmMultinomialVisualizer(MObjectSet objs) {
        initComponents();
        
        pnl = new PnlMultinomialVizualizer(objs);
        this.add(pnl);
        this.setVisible(true);
    }

    public void setValue(MultinomialDistribution dist) {
        pnl.setValue(dist);
    }
    
    public void setValue(Optional<MultinomialDistribution> dist) {
        pnl.setValue(dist);
    }

    public void setColor(Color c) {
        pnl.setColor(c);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 200));
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
