/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.brown.csci2951k.ui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Color;

/**
 *
 * @author Gaurav Manek
 */
class PnlBar extends javax.swing.JPanel {

    private double val = 0;
    private Color color = Color.BLUE;
    
    /**
     * Creates new form PnlBar
     */
    public PnlBar(String s) {
        initComponents();
        
        this.lblText.setText(s);
    }

    @Override
    public void paint(Graphics grphcs) {
        super.paint(grphcs); //To change body of generated methods, choose Tools | Templates.
        
        Graphics2D g = (Graphics2D) grphcs;
        
        int height = (int) (lblText.getY() * val);
        int y = lblText.getY() - height;
        g.setColor(this.color);
        g.fillRect(0, y, this.getWidth(), height);
    }

    public void setValue(double val) {
        if(val < 0 || val > 1) throw new IllegalArgumentException("val = ".concat(Double.toString(val)));
        this.val = val;
    }

    public void setColor(Color color) {
        this.color = color;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("jLabel1");
        add(lblText, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
